### PR TITLE
Remove asynctest

### PR DESCRIPTION
**Pull request by fabaff**
The asynctest is no longer supported and doesn't work with Python 3.11 (Martiusweb/asynctest#163).

### CODE REVIEW

**Comment by RicArch97** [comment]
Thanks!

**Comment by fabaff** [comment]
Could you please make a new release? Would be much appreciated by all package maintainers.

Thank you

**Comment by AlexDM0** [comment]
We're transitioning to the new repo crownstone-community. @RicArch97 I've added you as maintainer there, could you update the branches there? They're all forked from the crownstone repo.

https://github.com/crownstone-community

We'll release from there. Due to this transition, we still have to update the permissions for release.

We will not be developing on the Crownstone repo anymore. All the repositories have been forked to the Crownstone Community repo.

**Comment by RicArch97** [comment]
Done. We only have to do the release on PyPi as well. @AlexDM0 I assume you will take care of this?

**Comment by AlexDM0** [comment]
We'll take care of that. @mrquincle is on holiday at the moment and he'll take a look at the permissions for release. What is the version number you'd like for this?

**Comment by RicArch97** [comment]
Pushed a commit for a version bump to 1.4.10 [here](https://github.com/Crownstone-Community/crownstone-lib-python-cloud/commit/852c01cce4fef7a53c5c13bce8778e9c8b3fa270).

**Pull request merged**
